### PR TITLE
Update nREPL dependencies.

### PR DESCRIPTION
**Pull request by daveduthie**

### CODE REVIEW

**Comment by gregsh** [comment]
I'm a bit out of sync on this one. Please explain.

**Comment by nwjsmith** [comment]
@gregsh the nREPL project is now maintained outside of Clojure Contrib. See [the README](https://github.com/clojure/tools.nrepl#nrepl) or [this blog post with tons of background information](https://metaredux.com/posts/2018/10/29/nrepl-redux.html)

**Comment by daveduthie** [comment]
As @nwjsmith mentioned (thanks!), the nREPL project had a change of maintainers, and the artifact ID and namespaces had to be changed as part of the migration.

**Comment by gregsh** [comment]
Applied, thanks!

**Pull request closed without merging**
